### ISSUE TITLE
Does This Still Work

### ISSUE THREAD

**Issue by xpersonas** [evolvingweb/custom_field_resize#1]
I'm following this tutorial, but I'm still getting...  

`>  [error]  The SQL storage cannot change the schema for an existing field (field_special_information in product_entity entity) with data.`

**Comment by jigarius** [comment]
There have been many changes on Drupal entity update side of things. Maybe this is a result of such changes. I'll try to look into this and see if the example code still works.

Thanks for reporting the issue.
